version: '3.8'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment: 
      NEXTAUTH_URL: http://localhost:3000/
      GITHUB_CLIENT_ID: 
      GITHUB_SECRET: 
      GOOGLE_CLIENT_ID: 
      GOOGLE_SECRET: 
      OPENAI_ORGANIZATION: 
      OPENAI_API_KEY: 
      NEXTAUTH_SECRET: q6mZ5U#5,Y+%yH2SD-kShY9e6@X4Vr
      DATABASE_URL: "postgresql://usuario:contraseña@db/resumia?schema:public"

  db:
    image: postgres:15.4-alpine3.18
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t:9y++AXL9E3<YBR
      POSTGRES_DB: resumia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts/:/docker-entrypoint-initdb.d/

volumenes:
  postgres_data: